---
- hosts: arya
  remote_user: root
  sudo: no
  roles: 
    - hypervisor
  tasks: 
    - name: Set /usr/bin/vim as default editor
      command: /usr/bin/eselect editor set /usr/bin/vim
      #when: "$ENV(EDITOR)" != "/usr/bin/vim"
