" Vimrc file 
"
" Cannon Matthews 
" cannon@cannonmatthews.com 
" 2015-02-15 
"
" This file is managed by ansible. Edit on github.


" Vim defaults/boilerplate 
version 6.0
if &cp | set nocp | endif
let s:cpo_save=&cpo
set cpo&vim
imap <silent> <Plug>IMAP_JumpBack =IMAP_Jumpfunc('b', 0)
imap <silent> <Plug>IMAP_JumpForward =IMAP_Jumpfunc('', 0)
vmap <NL> <Plug>IMAP_JumpForward
nmap <NL> <Plug>IMAP_JumpForward
nmap gx <Plug>NetrwBrowseX
nnoremap <silent> <Plug>NetrwBrowseX :call netrw#NetrwBrowseX(expand("<cWORD>"),0)
vmap <silent> <Plug>IMAP_JumpBack `<i=IMAP_Jumpfunc('b', 0)
vmap <silent> <Plug>IMAP_JumpForward i=IMAP_Jumpfunc('', 0)
vmap <silent> <Plug>IMAP_DeleteAndJumpBack "_<Del>i=IMAP_Jumpfunc('b', 0)
vmap <silent> <Plug>IMAP_DeleteAndJumpForward "_<Del>i=IMAP_Jumpfunc('', 0)
nmap <silent> <Plug>IMAP_JumpBack i=IMAP_Jumpfunc('b', 0)
nmap <silent> <Plug>IMAP_JumpForward i=IMAP_Jumpfunc('', 0)
imap <NL> <Plug>IMAP_JumpForward
let &cpo=s:cpo_save
unlet s:cpo_save
set backspace=indent,eol,start
set fileencodings=ucs-bom,utf-8,latin1
set guicursor=n-v-c:block,o:hor50,i-ci:hor15,r-cr:hor30,sm:block,a:blinkon0
set helplang=en
set history=50
set hlsearch
set ruler
set viminfo='20,\"50
set nu                  " number lines
set mouse=a             " mouse in all modes 
set expandtab           " expand tabs to spaces 
set shiftwidth=2        " indent with N spaces at a time 
set softtabstop=2       " tab = 2 spaces 
set tabstop=2           " hardtab is 2 spaces 
set autoindent          " use autoindent for all files 
set modeline            " support modelines in files 
syntax on               " enable syntax highlighitng 


set foldmethod=manual   " do not automatically fold 
set foldnestmax=1       " up to 1 layer deep 
set foldlevelstart=0    " do not fold to start with 
let c_fold=1            " fold C files

" chdir to the dir of the current file/buffer
" look for ctags "tags" file in the current or parent dirs
" This allows you to have one tags file for a multi directory project 
set autochdir
set tags=tags; 

" ensure good colors 
set t_Co=265
colorscheme slate

" tab complete like bash 
set wildmode=longest,list,full

" Uncomment below to highight lines past 80 char as bright red
" TODO: make this something I can toggle 
"match ErrorMsg '\%>80v.\+'

" ```````````````` "
" vim latex things "
" ,,,,,,,,,,,,,,,, " 
" REQUIRED. This makes vim invoke Latex-Suite when you open a tex file.
filetype plugin on

" IMPORTANT: win32 users will need to have 'shellslash' set so that latex
" can be called correctly.
set shellslash

" IMPORTANT: grep will sometimes skip displaying the file name if you
" search in a singe file. This will confuse Latex-Suite. Set your grep
" program to always generate a file-name.
set grepprg=grep\ -nH\ $*

" OPTIONAL: This enables automatic indentation as you type.
filetype indent on

" OPTIONAL: Starting with Vim 7, the filetype of empty .tex files defaults to
" 'plaintex' instead of 'tex', which results in vim-latex not being loaded.
" The following changes the default filetype back to 'tex':
let g:tex_flavor='latex'
let g:Tex_DefaultTargetFormat = 'pdf'
let g:Tex_UseMakefile = 0
let g:Tex_CompileRule_pdf = 'make `basename $* .tex`'

"""""""""""""
" end latex "
"""""""""""""

" some homework submission header macros 
" @w - Haskell comment header 
let @w='gg:set formatoptions-=croOkki-- W. Cannon Matthews III -- CMSC 16100-- Exercise :r! date "+\%D"-- :set formatoptions+=crokA'
" @h -  generic unix script, # comments, leaves shebang in tact at top line 
let @h='gg:set formatoptions-=crookki# W. Cannon Matthews III # CMSC 16200# Exercise :r! date "+\%D"# :set formatoptions+=crokA'
" @c - Simple C boilerplate with comment at top, creates main and puts cursor
" there
let @c='i#include <stdifkbo.h>#include <stdlib.h> int main(int argc, char **argv) { argkbkbkbexit(0); }kkDkbkkkkkkkkO//%kbkbjjjjjji A       qkbkbkbkbi'


"" mode line for vimrc syntax highlighting 
" vim: set ft=vim :
