---
- name: add testing repo
  apt_repository: > 
        repo="deb http://mirrordirector.raspbian.org/raspbian testing main"
        state=present
- name: Install Packages
  apt: pkg={{item}} state=latest 
  with_items: packages
