---
- name: Install Webserver and Node.js
  apt: pkg={{item}} state=installed
  with_items: 
        - nodejs
        - npm
        - nginx
- name: Install TiddlyWiki Node app
  npm: > 
        name=tiddlywiki
        state=present
        global=yes
 
