---
# Playbook to create a remote management user, and give them sudo 
- hosts: all
  remote_user: cannonmatthews
  tasks: 
    - name: create Ansible Management user
      user: > 
        name=ansible
        createhome=yes
        home=/var/lib/ansible
        system=yes
        state=present
    - name: Install Authorized key file
      authorized_key: > 
        user=ansible
        state=present
        key="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBmUlltF9czCzO2iaOu5mEirig3wg5S4yFHPoEDxeEE54g3md2S+NqJzbro4XxzPSeQTrBgN7SyF0spU3ES7PNTV1DpIsBqUU9aX++yX5Uoi8l1u9ynMZ4GeN6TPdp+GyP9ebEFblYOZR8QQW/5tF9Jm1DizqRcQGgVmkE4Yvr8X2eAhRNL5yuNbfsyE7TqGhZprMx74dcCw8JqNyn9tvfGVZ65q//+hGEbmskphvbo+rqxkzTQMpgMpa73qpv3kQrd4RJy8zKJOe8EJQsxYUcaDF06FcHR6+qfMMbH1dHZ2gWrMqtuFtASeiYoMIVrg+PJU6bFU7dJjuTL4KFv/vF cannonmatthews@jane.lan.cannonmatthews.com" 
    - name: install sudo (yum) 
      yum: name=sudo state=installed
      when: ansible_pkg_mgr == 'yum'
    - name: install sudo (apt) 
      apt: name=sudo state=installed
      when: ansible_pkg_mgr == 'apt'
    - name: Give Sudo access to user
      lineinfile: >
        dest=/etc/sudoers 
        state=present 
        regexp='^%ansible' 
        line='%ansible ALL=(root) NOPASSWD:ALL' 
        validate='visudo -cf %s'


